Pandora fun
FNALssi/fnal_art pull request #28
Opened 2023-08-11 19:19 UTC by marcmengel

So we needed a patch, but the way the build works we have to apply it in a weird way... 
Basically the package initially has almost no code in it and the ExternalPackage stuff
pulls it down, so we have to build part of it, apply the patch, and rebuild...

2023-08-12 18:35 UTC, marcmengel commented
... and bxdecay0 updates.

2023-08-15 17:39 UTC, greenc-FNAL requested changes
I would suggest we document the reason for the patch and any applicable bug reports or other links too.

2023-08-15 17:39 UTC, greenc-FNAL commented on packages/pandora/package.py
> +            "-DiINSTALL_DOC=OFF",
Should that be
```.py
            "-DINSTALL_DOC=OFF",
```
?

2023-08-15 18:14 UTC, marcmengel commented on packages/pandora/package.py
> +            "-DiINSTALL_DOC=OFF",
Updated as requested.

2023-08-15 19:34 UTC, merged