Disallow C++17 for art-suite@develop, etc.
FNALssi/fnal_art pull request #48
Opened 2023-11-13 17:30 UTC by knoepfel

Includes:

- Forbidding C++17 when installing `@develop` (only C++20 and above is supported)
- Constraining Boost to `cxxstd=11` when using Boost JSON (otherwise it won't build/install)
- Miscellaneous whitespace cleanups

2023-11-16 14:53 UTC, knoepfel commented
Ping

2023-11-27 15:04 UTC, knoepfel commented
Ping

2023-11-27 15:35 UTC, marcmengel requested changes
Could we make the --preset default bits contingent on either the preset file being present, or the package version?  Older versions don't have this...

2023-11-27 22:22 UTC, marcmengel approved these changes
Looks good!

2023-11-27 22:22 UTC, merged